/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import com.team14.se.maintenanceapp.Competence;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;

/**
 *
 * @author mario
 */
public class CompetencePanel extends javax.swing.JPanel {
    
    private LinkedList<Competence> competences;
    private LinkedList<Competence> selectedCompetences = null;
    private Connection connection;
    private DefaultListModel<String> competencesListModel;

    /**
     * Creates new form CompetencePanel
     */
    public CompetencePanel() {
        this.competencesListModel = new DefaultListModel<>();
        initComponents();
    }
    
    public CompetencePanel(Connection connection) {
        this.competencesListModel = new DefaultListModel<>();
        this.connection = connection;
        initComponents();
        
        this.competencesJList.addListSelectionListener((ListSelectionEvent event) -> { 
            this.removeCompetencesJButton.setEnabled(true);
        });
    }
    
    public LinkedList<String> getSelectedCompetences() {
        return new LinkedList<>(Arrays.asList((String[])this.competencesListModel.toArray()));
    }
    
    public void activate(LinkedList<Competence> selectedCompetences) throws SQLException{
        this.addCompetencesJComboBox.removeAllItems();
        this.competencesListModel.clear();
        
        setEnabled(true);
        this.selectedCompetences = selectedCompetences;
        this.competences = Competence.getCompetences(connection);
        
        this.competencesListModel = new DefaultListModel<>();
        
        this.selectedCompetences.forEach(competence -> {
            this.competencesListModel.addElement(competence.getName());
        });
        this.competencesJList.setModel(competencesListModel);
        
        this.competences.removeAll(this.selectedCompetences);

        this.competences.forEach(competence -> {
            addCompetencesJComboBox.addItem(competence.getName());
        });
        
        this.competencesJScrollPane.setEnabled(true);
        this.competencesJList.setEnabled(true);
        
        this.addCompetencesJPanel.setEnabled(true);
        this.addCompetencesJComboBox.setEnabled(true);
        
        if (this.competences.size() > 0){
            this.addCompetencesJButton.setEnabled(true);
        }
    }

    public void deactivate(){
        this.competencesListModel.clear();
        this.addCompetencesJComboBox.removeAllItems();
                
        setEnabled(false);
        this.competencesJScrollPane.setEnabled(false);
        this.competencesJList.setEnabled(false);
        
        this.addCompetencesJPanel.setEnabled(false);
        this.addCompetencesJComboBox.setEnabled(false);
        this.addCompetencesJButton.setEnabled(false);
        this.removeCompetencesJButton.setEnabled(false);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        competencesJScrollPane = new javax.swing.JScrollPane();
        competencesJList = new javax.swing.JList<>();
        removeCompetencesJButton = new javax.swing.JButton();
        addCompetencesJPanel = new javax.swing.JPanel();
        addCompetencesJButton = new javax.swing.JButton();
        addCompetencesJComboBox = new javax.swing.JComboBox<>();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Competences"));

        competencesJList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        competencesJList.setEnabled(false);
        competencesJScrollPane.setViewportView(competencesJList);

        removeCompetencesJButton.setText("Remove Selected");
        removeCompetencesJButton.setEnabled(false);
        removeCompetencesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCompetencesJButtonActionPerformed(evt);
            }
        });

        addCompetencesJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Competences"));
        addCompetencesJPanel.setEnabled(false);

        addCompetencesJButton.setText("Add ");
        addCompetencesJButton.setEnabled(false);
        addCompetencesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCompetencesJButtonActionPerformed(evt);
            }
        });

        addCompetencesJComboBox.setEnabled(false);

        javax.swing.GroupLayout addCompetencesJPanelLayout = new javax.swing.GroupLayout(addCompetencesJPanel);
        addCompetencesJPanel.setLayout(addCompetencesJPanelLayout);
        addCompetencesJPanelLayout.setHorizontalGroup(
            addCompetencesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCompetencesJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addCompetencesJComboBox, 0, 230, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addCompetencesJButton)
                .addContainerGap())
        );
        addCompetencesJPanelLayout.setVerticalGroup(
            addCompetencesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCompetencesJPanelLayout.createSequentialGroup()
                .addGroup(addCompetencesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCompetencesJButton)
                    .addComponent(addCompetencesJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(competencesJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(88, 88, 88))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addCompetencesJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(removeCompetencesJButton)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(competencesJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeCompetencesJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addCompetencesJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addCompetencesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCompetencesJButtonActionPerformed
        this.competencesListModel.addElement(this.addCompetencesJComboBox.getSelectedItem().toString());
        this.addCompetencesJComboBox.removeItem(this.addCompetencesJComboBox.getSelectedItem());
        if (this.addCompetencesJComboBox.getItemCount() < 1){
            this.addCompetencesJButton.setEnabled(false);
        }
        this.removeCompetencesJButton.setEnabled(false);
    }//GEN-LAST:event_addCompetencesJButtonActionPerformed

    private void removeCompetencesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCompetencesJButtonActionPerformed
        this.addCompetencesJComboBox.addItem(this.competencesJList.getSelectedValue());
        this.competencesListModel.removeElement(this.competencesJList.getSelectedValue());
        if (this.addCompetencesJComboBox.getItemCount() > 0){
            this.addCompetencesJButton.setEnabled(true);
        }
        this.removeCompetencesJButton.setEnabled(false);
    }//GEN-LAST:event_removeCompetencesJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCompetencesJButton;
    private javax.swing.JComboBox<String> addCompetencesJComboBox;
    private javax.swing.JPanel addCompetencesJPanel;
    private javax.swing.JList<String> competencesJList;
    private javax.swing.JScrollPane competencesJScrollPane;
    private javax.swing.JButton removeCompetencesJButton;
    // End of variables declaration//GEN-END:variables
}
