/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author mario
 */
public class PlannerGUI extends javax.swing.JFrame {

    /**
     * Creates new form MantainerGUI
     */
    public PlannerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        interrruptableButtonGroup = new javax.swing.ButtonGroup();
        eowButtonGroup = new javax.swing.ButtonGroup();
        mainJTabbedPane = new javax.swing.JTabbedPane();
        assignTabJPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        refreshJButton = new javax.swing.JButton();
        weekNumberJLabel = new javax.swing.JLabel();
        weekNumberJSpinner = new javax.swing.JSpinner();
        detailsJPanel = new javax.swing.JPanel();
        detailsWeekJLabel = new javax.swing.JLabel();
        detailsActivityJLabel = new javax.swing.JLabel();
        detailsSMPJLabel = new javax.swing.JLabel();
        detailsWeekJTextField = new javax.swing.JTextField();
        detailsActivityJTextField = new javax.swing.JTextField();
        detailsSMPJTextField = new javax.swing.JTextField();
        detailsDescriptionJScrollPanel = new javax.swing.JScrollPane();
        detailsDescriptionJTextArea = new javax.swing.JTextArea();
        detailsSkillsJScrollPane = new javax.swing.JScrollPane();
        detailsSkillsJList = new javax.swing.JList<>();
        detailsNotesJScrollPane = new javax.swing.JScrollPane();
        detailsNotesJTextArea = new javax.swing.JTextArea();
        forwardJButton = new javax.swing.JButton();
        activitiesTableJScrollPane = new javax.swing.JScrollPane();
        activitiesJTable = new javax.swing.JTable();
        addJPanel = new javax.swing.JPanel();
        nameJLabel = new javax.swing.JLabel();
        weekJLabel = new javax.swing.JLabel();
        typeJLabel = new javax.swing.JLabel();
        procedureJLabel = new javax.swing.JLabel();
        siteJLabel = new javax.swing.JLabel();
        estimatedTimeJLabel = new javax.swing.JLabel();
        ewoJLabel1 = new javax.swing.JLabel();
        descriptionJScrollPane = new javax.swing.JScrollPane();
        descriptionJTextArea = new javax.swing.JTextArea();
        addJButton = new javax.swing.JButton();
        nameJTextField = new javax.swing.JTextField();
        interruptJLabel = new javax.swing.JLabel();
        interruptYesJRadioButton = new javax.swing.JRadioButton();
        interruptNoJRadioButton = new javax.swing.JRadioButton();
        estimatedTimeJSpinner = new javax.swing.JSpinner();
        weekJSpinner = new javax.swing.JSpinner();
        typeJComboBox = new javax.swing.JComboBox<>();
        procedureJComboBox = new javax.swing.JComboBox<>();
        siteJComboBox = new javax.swing.JComboBox<>();
        ewoYesJRadioButton = new javax.swing.JRadioButton();
        ewoNoJRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        assignTabJPanel.setLayout(new java.awt.BorderLayout());

        refreshJButton.setText("Refresh List");

        weekNumberJLabel.setText("Week N.");

        weekNumberJSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 53, 1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(weekNumberJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weekNumberJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshJButton)
                    .addComponent(weekNumberJLabel)
                    .addComponent(weekNumberJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        assignTabJPanel.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        detailsJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Selected Activity Details"));

        detailsWeekJLabel.setText("Week N.");

        detailsActivityJLabel.setText("Activity To assign");

        detailsSMPJLabel.setText("SMP");

        detailsWeekJTextField.setText("--");
        detailsWeekJTextField.setEnabled(false);
        detailsWeekJTextField.setFocusable(false);

        detailsActivityJTextField.setEnabled(false);
        detailsActivityJTextField.setFocusable(false);

        detailsSMPJTextField.setEnabled(false);
        detailsSMPJTextField.setFocusable(false);

        detailsDescriptionJScrollPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Description"));

        detailsDescriptionJTextArea.setColumns(20);
        detailsDescriptionJTextArea.setRows(5);
        detailsDescriptionJTextArea.setEnabled(false);
        detailsDescriptionJTextArea.setFocusable(false);
        detailsDescriptionJScrollPanel.setViewportView(detailsDescriptionJTextArea);

        detailsSkillsJScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Skills Nedded"));

        detailsSkillsJList.setEnabled(false);
        detailsSkillsJScrollPane.setViewportView(detailsSkillsJList);

        detailsNotesJScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Workspace Notes"));

        detailsNotesJTextArea.setColumns(20);
        detailsNotesJTextArea.setRows(5);
        detailsNotesJTextArea.setEnabled(false);
        detailsNotesJTextArea.setFocusable(false);
        detailsNotesJScrollPane.setViewportView(detailsNotesJTextArea);

        forwardJButton.setText("Forward");

        javax.swing.GroupLayout detailsJPanelLayout = new javax.swing.GroupLayout(detailsJPanel);
        detailsJPanel.setLayout(detailsJPanelLayout);
        detailsJPanelLayout.setHorizontalGroup(
            detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(detailsDescriptionJScrollPanel)
                    .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(detailsJPanelLayout.createSequentialGroup()
                            .addComponent(detailsWeekJLabel)
                            .addGap(18, 18, 18)
                            .addComponent(detailsWeekJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, detailsJPanelLayout.createSequentialGroup()
                                .addComponent(detailsSMPJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(detailsSMPJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, detailsJPanelLayout.createSequentialGroup()
                                .addComponent(detailsActivityJLabel)
                                .addGap(18, 18, 18)
                                .addComponent(detailsActivityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(detailsSkillsJScrollPane)
                    .addComponent(detailsNotesJScrollPane))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailsJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(forwardJButton)
                .addContainerGap())
        );
        detailsJPanelLayout.setVerticalGroup(
            detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsJPanelLayout.createSequentialGroup()
                .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detailsWeekJLabel)
                    .addComponent(detailsWeekJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detailsActivityJLabel)
                    .addComponent(detailsActivityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detailsSMPJLabel)
                    .addComponent(detailsSMPJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(detailsDescriptionJScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(detailsSkillsJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(detailsNotesJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(forwardJButton)
                .addContainerGap())
        );

        assignTabJPanel.add(detailsJPanel, java.awt.BorderLayout.LINE_END);

        activitiesTableJScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Maintenance Activities"));

        activitiesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Area", "Type", "EIT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        activitiesJTable.getTableHeader().setReorderingAllowed(false);
        activitiesTableJScrollPane.setViewportView(activitiesJTable);

        assignTabJPanel.add(activitiesTableJScrollPane, java.awt.BorderLayout.CENTER);

        mainJTabbedPane.addTab("Assign Activity", assignTabJPanel);

        nameJLabel.setText("Name");

        weekJLabel.setText("Week");

        typeJLabel.setText("Type");

        procedureJLabel.setText("Procedure");

        siteJLabel.setText("Site");

        estimatedTimeJLabel.setText("Estimated time");

        ewoJLabel1.setText("EWO");

        descriptionJScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Description"));

        descriptionJTextArea.setColumns(20);
        descriptionJTextArea.setRows(5);
        descriptionJScrollPane.setViewportView(descriptionJTextArea);

        addJButton.setText("Add");

        interruptJLabel.setText("Interruptable");

        interrruptableButtonGroup.add(interruptYesJRadioButton);
        interruptYesJRadioButton.setText("Yes");

        interrruptableButtonGroup.add(interruptNoJRadioButton);
        interruptNoJRadioButton.setSelected(true);
        interruptNoJRadioButton.setText("No");

        estimatedTimeJSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        weekJSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 53, 1));

        eowButtonGroup.add(ewoYesJRadioButton);
        ewoYesJRadioButton.setText("Yes");

        eowButtonGroup.add(ewoNoJRadioButton);
        ewoNoJRadioButton.setSelected(true);
        ewoNoJRadioButton.setText("No");

        javax.swing.GroupLayout addJPanelLayout = new javax.swing.GroupLayout(addJPanel);
        addJPanel.setLayout(addJPanelLayout);
        addJPanelLayout.setHorizontalGroup(
            addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addJPanelLayout.createSequentialGroup()
                        .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estimatedTimeJLabel)
                            .addComponent(interruptJLabel))
                        .addGap(50, 50, 50)
                        .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addJPanelLayout.createSequentialGroup()
                                .addComponent(interruptYesJRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(interruptNoJRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(estimatedTimeJSpinner)))
                    .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(addJPanelLayout.createSequentialGroup()
                            .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nameJLabel)
                                .addComponent(weekJLabel))
                            .addGap(109, 109, 109)
                            .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(addJPanelLayout.createSequentialGroup()
                            .addComponent(ewoJLabel1)
                            .addGap(119, 119, 119)
                            .addComponent(ewoYesJRadioButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ewoNoJRadioButton))
                        .addGroup(addJPanelLayout.createSequentialGroup()
                            .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(typeJLabel)
                                .addComponent(procedureJLabel)
                                .addComponent(siteJLabel))
                            .addGap(83, 83, 83)
                            .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(typeJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(procedureJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(siteJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(weekJSpinner)))))
                .addGap(448, 448, 448))
            .addGroup(addJPanelLayout.createSequentialGroup()
                .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addJButton)
                    .addComponent(descriptionJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        addJPanelLayout.setVerticalGroup(
            addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameJLabel)
                    .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weekJLabel)
                    .addComponent(weekJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeJLabel)
                    .addComponent(typeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(procedureJLabel)
                    .addComponent(procedureJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(siteJLabel)
                    .addComponent(siteJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estimatedTimeJLabel)
                    .addComponent(estimatedTimeJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(interruptJLabel)
                    .addComponent(interruptYesJRadioButton)
                    .addComponent(interruptNoJRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ewoJLabel1)
                    .addComponent(ewoYesJRadioButton)
                    .addComponent(ewoNoJRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addJButton)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        mainJTabbedPane.addTab("Add New Activity", addJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainJTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainJTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlannerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlannerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlannerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlannerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlannerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable activitiesJTable;
    private javax.swing.JScrollPane activitiesTableJScrollPane;
    private javax.swing.JButton addJButton;
    private javax.swing.JPanel addJPanel;
    private javax.swing.JPanel assignTabJPanel;
    private javax.swing.JScrollPane descriptionJScrollPane;
    private javax.swing.JTextArea descriptionJTextArea;
    private javax.swing.JLabel detailsActivityJLabel;
    private javax.swing.JTextField detailsActivityJTextField;
    private javax.swing.JScrollPane detailsDescriptionJScrollPanel;
    private javax.swing.JTextArea detailsDescriptionJTextArea;
    private javax.swing.JPanel detailsJPanel;
    private javax.swing.JScrollPane detailsNotesJScrollPane;
    private javax.swing.JTextArea detailsNotesJTextArea;
    private javax.swing.JLabel detailsSMPJLabel;
    private javax.swing.JTextField detailsSMPJTextField;
    private javax.swing.JList<String> detailsSkillsJList;
    private javax.swing.JScrollPane detailsSkillsJScrollPane;
    private javax.swing.JLabel detailsWeekJLabel;
    private javax.swing.JTextField detailsWeekJTextField;
    private javax.swing.ButtonGroup eowButtonGroup;
    private javax.swing.JLabel estimatedTimeJLabel;
    private javax.swing.JSpinner estimatedTimeJSpinner;
    private javax.swing.JLabel ewoJLabel1;
    private javax.swing.JRadioButton ewoNoJRadioButton;
    private javax.swing.JRadioButton ewoYesJRadioButton;
    private javax.swing.JButton forwardJButton;
    private javax.swing.ButtonGroup interrruptableButtonGroup;
    private javax.swing.JLabel interruptJLabel;
    private javax.swing.JRadioButton interruptNoJRadioButton;
    private javax.swing.JRadioButton interruptYesJRadioButton;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane mainJTabbedPane;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JComboBox<String> procedureJComboBox;
    private javax.swing.JLabel procedureJLabel;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JComboBox<String> siteJComboBox;
    private javax.swing.JLabel siteJLabel;
    private javax.swing.JComboBox<String> typeJComboBox;
    private javax.swing.JLabel typeJLabel;
    private javax.swing.JLabel weekJLabel;
    private javax.swing.JSpinner weekJSpinner;
    private javax.swing.JLabel weekNumberJLabel;
    private javax.swing.JSpinner weekNumberJSpinner;
    // End of variables declaration//GEN-END:variables
}
