/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import com.team14.se.maintenanceapp.*;
import com.team14.se.maintenanceapp.User;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Enumeration;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mario
 */
public class PlannerGUI extends javax.swing.JFrame {

    private User loggedUser;
    private Connection connection;
    private LinkedList<MaintenanceActivity> activityList;

    /**
     * Creates new form MantainerGUI
     */
    public PlannerGUI() {
        initComponents();
    }

    /**
     * Creates new form MantainerGUI
     *
     * @param loggedUser the logged user
     * @param connection the database connection
     */
    public PlannerGUI(User loggedUser, Connection connection) {
        this.loggedUser = loggedUser;
        this.connection = connection;
        initComponents();
        initValues();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        interrruptableButtonGroup = new javax.swing.ButtonGroup();
        eowButtonGroup = new javax.swing.ButtonGroup();
        mainJTabbedPane = new javax.swing.JTabbedPane();
        assignTabJPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        refreshJButton = new javax.swing.JButton();
        weekNumberJLabel = new javax.swing.JLabel();
        weekNumberJSpinner = new javax.swing.JSpinner();
        detailsJPanel = new javax.swing.JPanel();
        detailsWeekJLabel = new javax.swing.JLabel();
        detailsActivityJLabel = new javax.swing.JLabel();
        detailsSMPJLabel = new javax.swing.JLabel();
        detailsWeekJTextField = new javax.swing.JTextField();
        detailsActivityJTextField = new javax.swing.JTextField();
        detailsSMPJTextField = new javax.swing.JTextField();
        detailsDescriptionJScrollPanel = new javax.swing.JScrollPane();
        detailsDescriptionJTextArea = new javax.swing.JTextArea();
        detailsSkillsJScrollPane = new javax.swing.JScrollPane();
        detailsSkillsJList = new javax.swing.JList<>();
        detailsNotesJScrollPane = new javax.swing.JScrollPane();
        detailsNotesJTextArea = new javax.swing.JTextArea();
        forwardJButton = new javax.swing.JButton();
        assignJLabel = new javax.swing.JLabel();
        assignJComboBox = new javax.swing.JComboBox<>();
        detailsIdJLabel = new javax.swing.JLabel();
        detailsIdJTextField = new javax.swing.JTextField();
        activitiesTableJScrollPane = new javax.swing.JScrollPane();
        activitiesJTable = new javax.swing.JTable();
        addJPanel = new javax.swing.JPanel();
        nameJLabel = new javax.swing.JLabel();
        weekJLabel = new javax.swing.JLabel();
        typeJLabel = new javax.swing.JLabel();
        procedureJLabel = new javax.swing.JLabel();
        siteJLabel = new javax.swing.JLabel();
        estimatedTimeJLabel = new javax.swing.JLabel();
        ewoJLabel1 = new javax.swing.JLabel();
        descriptionJScrollPane = new javax.swing.JScrollPane();
        descriptionJTextArea = new javax.swing.JTextArea();
        addJButton = new javax.swing.JButton();
        nameJTextField = new javax.swing.JTextField();
        interruptJLabel = new javax.swing.JLabel();
        interruptYesJRadioButton = new javax.swing.JRadioButton();
        interruptNoJRadioButton = new javax.swing.JRadioButton();
        estimatedTimeJSpinner = new javax.swing.JSpinner();
        weekJSpinner = new javax.swing.JSpinner();
        typeJComboBox = new javax.swing.JComboBox<>();
        procedureJComboBox = new javax.swing.JComboBox<>();
        siteJComboBox = new javax.swing.JComboBox<>();
        ewoYesJRadioButton = new javax.swing.JRadioButton();
        ewoNoJRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        assignTabJPanel.setLayout(new java.awt.BorderLayout());

        refreshJButton.setText("Refresh List");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        weekNumberJLabel.setText("Week N.");

        weekNumberJSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 53, 1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(weekNumberJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weekNumberJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(refreshJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshJButton)
                    .addComponent(weekNumberJLabel)
                    .addComponent(weekNumberJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        assignTabJPanel.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        detailsJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Selected Activity Details"));

        detailsWeekJLabel.setText("Week N.");

        detailsActivityJLabel.setText("Activity To assign");

        detailsSMPJLabel.setText("SMP");

        detailsWeekJTextField.setText("--");
        detailsWeekJTextField.setDisabledTextColor(new java.awt.Color(89, 89, 89));
        detailsWeekJTextField.setEnabled(false);
        detailsWeekJTextField.setFocusable(false);

        detailsActivityJTextField.setEnabled(false);
        detailsActivityJTextField.setFocusable(false);

        detailsSMPJTextField.setEnabled(false);
        detailsSMPJTextField.setFocusable(false);
        detailsSMPJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsSMPJTextFieldActionPerformed(evt);
            }
        });

        detailsDescriptionJScrollPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Description"));

        detailsDescriptionJTextArea.setColumns(20);
        detailsDescriptionJTextArea.setRows(5);
        detailsDescriptionJTextArea.setEnabled(false);
        detailsDescriptionJTextArea.setFocusable(false);
        detailsDescriptionJScrollPanel.setViewportView(detailsDescriptionJTextArea);

        detailsSkillsJScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Skills Nedded"));

        detailsSkillsJList.setEnabled(false);
        detailsSkillsJScrollPane.setViewportView(detailsSkillsJList);

        detailsNotesJScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Workspace Notes"));

        detailsNotesJTextArea.setColumns(20);
        detailsNotesJTextArea.setRows(5);
        detailsNotesJTextArea.setText("Notes will be implemented in sprint 2");
        detailsNotesJTextArea.setEnabled(false);
        detailsNotesJTextArea.setFocusable(false);
        detailsNotesJScrollPane.setViewportView(detailsNotesJTextArea);

        forwardJButton.setText("Forward");
        forwardJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forwardJButtonActionPerformed(evt);
            }
        });

        assignJLabel.setText("Assigned to");

        detailsIdJLabel.setText("Id activity");

        detailsIdJTextField.setText("--");
        detailsIdJTextField.setDisabledTextColor(new java.awt.Color(89, 89, 89));
        detailsIdJTextField.setEnabled(false);
        detailsIdJTextField.setFocusable(false);

        javax.swing.GroupLayout detailsJPanelLayout = new javax.swing.GroupLayout(detailsJPanel);
        detailsJPanel.setLayout(detailsJPanelLayout);
        detailsJPanelLayout.setHorizontalGroup(
            detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailsJPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(forwardJButton))
                    .addGroup(detailsJPanelLayout.createSequentialGroup()
                        .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(detailsDescriptionJScrollPanel)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, detailsJPanelLayout.createSequentialGroup()
                                .addComponent(detailsSMPJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(detailsSMPJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(detailsSkillsJScrollPane)
                            .addComponent(detailsNotesJScrollPane)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, detailsJPanelLayout.createSequentialGroup()
                                .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(detailsActivityJLabel)
                                    .addGroup(detailsJPanelLayout.createSequentialGroup()
                                        .addComponent(detailsWeekJLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(detailsWeekJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(detailsJPanelLayout.createSequentialGroup()
                                        .addComponent(detailsIdJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(detailsIdJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(detailsActivityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(detailsJPanelLayout.createSequentialGroup()
                        .addComponent(assignJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(assignJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        detailsJPanelLayout.setVerticalGroup(
            detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsJPanelLayout.createSequentialGroup()
                .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(detailsIdJLabel)
                        .addComponent(detailsIdJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(detailsWeekJLabel)
                        .addComponent(detailsWeekJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detailsActivityJLabel)
                    .addComponent(detailsActivityJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(detailsSMPJLabel)
                    .addComponent(detailsSMPJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(detailsDescriptionJScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailsSkillsJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(detailsNotesJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(detailsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignJLabel)
                    .addComponent(assignJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(forwardJButton)
                .addContainerGap())
        );

        assignTabJPanel.add(detailsJPanel, java.awt.BorderLayout.LINE_END);

        activitiesTableJScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Maintenance Activities"));

        activitiesJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "ID", "Area", "Type", "EIT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        activitiesJTable.getTableHeader().setReorderingAllowed(false);
        activitiesJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                activitiesJTableMouseClicked(evt);
            }
        });
        activitiesTableJScrollPane.setViewportView(activitiesJTable);

        assignTabJPanel.add(activitiesTableJScrollPane, java.awt.BorderLayout.CENTER);

        mainJTabbedPane.addTab("Assign Activity", assignTabJPanel);

        nameJLabel.setText("Name");

        weekJLabel.setText("Week");

        typeJLabel.setText("Type");

        procedureJLabel.setText("Procedure");

        siteJLabel.setText("Site");

        estimatedTimeJLabel.setText("Estimated time");

        ewoJLabel1.setText("EWO");

        descriptionJScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Description"));

        descriptionJTextArea.setColumns(20);
        descriptionJTextArea.setRows(5);
        descriptionJScrollPane.setViewportView(descriptionJTextArea);

        addJButton.setText("Add");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });

        interruptJLabel.setText("Interruptable");

        interrruptableButtonGroup.add(interruptYesJRadioButton);
        interruptYesJRadioButton.setText("Yes");

        interrruptableButtonGroup.add(interruptNoJRadioButton);
        interruptNoJRadioButton.setSelected(true);
        interruptNoJRadioButton.setText("No");

        estimatedTimeJSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        weekJSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 53, 1));

        eowButtonGroup.add(ewoYesJRadioButton);
        ewoYesJRadioButton.setText("Yes");
        ewoYesJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ewoYesJRadioButtonActionPerformed(evt);
            }
        });

        eowButtonGroup.add(ewoNoJRadioButton);
        ewoNoJRadioButton.setSelected(true);
        ewoNoJRadioButton.setText("No");

        javax.swing.GroupLayout addJPanelLayout = new javax.swing.GroupLayout(addJPanel);
        addJPanel.setLayout(addJPanelLayout);
        addJPanelLayout.setHorizontalGroup(
            addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addJPanelLayout.createSequentialGroup()
                        .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estimatedTimeJLabel)
                            .addComponent(interruptJLabel))
                        .addGap(50, 50, 50)
                        .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addJPanelLayout.createSequentialGroup()
                                .addComponent(interruptYesJRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(interruptNoJRadioButton))
                            .addComponent(estimatedTimeJSpinner)))
                    .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(addJPanelLayout.createSequentialGroup()
                            .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nameJLabel)
                                .addComponent(weekJLabel))
                            .addGap(109, 109, 109)
                            .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(addJPanelLayout.createSequentialGroup()
                            .addComponent(ewoJLabel1)
                            .addGap(119, 119, 119)
                            .addComponent(ewoYesJRadioButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ewoNoJRadioButton))
                        .addGroup(addJPanelLayout.createSequentialGroup()
                            .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(typeJLabel)
                                .addComponent(procedureJLabel)
                                .addComponent(siteJLabel))
                            .addGap(83, 83, 83)
                            .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(typeJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(procedureJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(siteJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(weekJSpinner)))))
                .addGap(448, 448, 448))
            .addGroup(addJPanelLayout.createSequentialGroup()
                .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addJButton)
                    .addComponent(descriptionJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        addJPanelLayout.setVerticalGroup(
            addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameJLabel)
                    .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(weekJLabel)
                    .addComponent(weekJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeJLabel)
                    .addComponent(typeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(procedureJLabel)
                    .addComponent(procedureJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(siteJLabel)
                    .addComponent(siteJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estimatedTimeJLabel)
                    .addComponent(estimatedTimeJSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(interruptJLabel)
                    .addComponent(interruptYesJRadioButton)
                    .addComponent(interruptNoJRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ewoJLabel1)
                    .addComponent(ewoYesJRadioButton)
                    .addComponent(ewoNoJRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addJButton)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        mainJTabbedPane.addTab("Add New Activity", addJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainJTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainJTabbedPane)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        int week_n = (int) weekNumberJSpinner.getValue();
        initTable(week_n);
        detailsNotesJTextArea.setEnabled(false);
        detailsWeekJTextField.setText("--");
        detailsSMPJTextField.setText("");
        detailsActivityJTextField.setText("");
        detailsDescriptionJTextArea.setText("");
        detailsIdJTextField.setText("");
        detailsSkillsJList.removeAll();
    }//GEN-LAST:event_refreshJButtonActionPerformed

    private String getButtonText(ButtonGroup buttonGroup) {
        String value = null;
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                value = button.getText();
            }
        }
        return value;
    }

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        MaintenanceActivity maintenanceActivity;
        String description = descriptionJTextArea.getText();
        String name = nameJTextField.getText();
        String typology = String.valueOf(typeJComboBox.getSelectedItem());
        String procedure = String.valueOf(procedureJComboBox.getSelectedItem());
        String site = String.valueOf(siteJComboBox.getSelectedItem());
        int week = (int) weekJSpinner.getValue();
        int estimatedTime = (int) estimatedTimeJSpinner.getValue();
        boolean interrruptable;
        if (getButtonText(interrruptableButtonGroup).equals("Yes")) {
            interrruptable = true;
        } else {
            interrruptable = false;
        }
        boolean ewo;
        if (getButtonText(eowButtonGroup).equals("Yes")) {
            ewo = true;
        } else {
            ewo = false;
        }

        maintenanceActivity = new MaintenanceActivity(name, description, interrruptable, estimatedTime, ewo, week, new Procedure(procedure, "", new LinkedList<>()), new Site(site), new Typology(typology), " ");
        int input = JOptionPane.showConfirmDialog(rootPane,
                "Are you sure you want to create this activity?",
                "Select an Option...", JOptionPane.YES_NO_CANCEL_OPTION);
        if (input == 0) {
            try {
                MaintenanceActivity.addMaintenanceActivity(connection, maintenanceActivity);
                JOptionPane.showMessageDialog(rootPane, "Activity created successfully");
            } catch (SQLException ex) {
                Logger.getLogger(PlannerGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Operation canceled");
        }


    }//GEN-LAST:event_addJButtonActionPerformed

    private void ewoYesJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ewoYesJRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ewoYesJRadioButtonActionPerformed

    private void activitiesJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_activitiesJTableMouseClicked
        JTable source = (JTable) evt.getSource();
        int row = source.rowAtPoint(evt.getPoint());
        String id = source.getModel().getValueAt(row, 0) + "";
        activityList.forEach((MaintenanceActivity activity) -> {
            if (activity.getActivityId() == Integer.parseInt(id)) {
                detailsActivityJTextField.setText(activity.getName());
                detailsIdJTextField.setText(id);
                detailsWeekJTextField.setText(String.valueOf(activity.getWeek()));
                detailsSMPJTextField.setText(activity.getProcedure().getSmpName());
                detailsDescriptionJTextArea.setText(activity.getDescription());
                DefaultListModel listModel = new DefaultListModel();
                LinkedList<Competence> competenceList = activity.getProcedure().getProcedureCompetences();
                competenceList.forEach(competence -> {
                    listModel.addElement(competence.getName());
                });
                detailsSkillsJList.setModel(listModel);
                detailsNotesJTextArea.setEnabled(true);
                assignJComboBox.setEnabled(true);
                forwardJButton.setEnabled(true);

            }
        });

    }//GEN-LAST:event_activitiesJTableMouseClicked

    private void detailsSMPJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsSMPJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailsSMPJTextFieldActionPerformed

    private void forwardJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forwardJButtonActionPerformed
        if (detailsWeekJTextField.getText().equals("--")) {
            JOptionPane.showMessageDialog(rootPane, "Please, select an activity to assign to the maintenance", "Error: No activity selected", JOptionPane.ERROR_MESSAGE);
        } else {
            String activityId = detailsIdJTextField.getText();
            String usernameMaintainer = String.valueOf(assignJComboBox.getSelectedItem()).split(":")[0];

            int input = JOptionPane.showConfirmDialog(rootPane,
                    "Are you sure to assign activity " + activityId + " to : " + usernameMaintainer + "?",
                    "Select an Option...", JOptionPane.YES_NO_CANCEL_OPTION);

            if (input == 0) {
                try {
                    PreparedStatement statementForAssign;
                    String queryForAssign = "INSERT INTO ESECUZIONE(activity_id,maintainer) VALUES (?,?);";
                    statementForAssign = connection.prepareStatement(queryForAssign);
                    statementForAssign.setInt(1, Integer.parseInt(activityId));
                    statementForAssign.setString(2, usernameMaintainer);
                    statementForAssign.executeUpdate();
                    JOptionPane.showMessageDialog(rootPane, "Task assigned correctly");

                } catch (SQLException ex) {
                    Logger.getLogger(PlannerGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Assignment canceled");
            }

        }
        //Statement statement = connection.createStatement();

    }//GEN-LAST:event_forwardJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlannerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlannerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlannerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlannerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlannerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable activitiesJTable;
    private javax.swing.JScrollPane activitiesTableJScrollPane;
    private javax.swing.JButton addJButton;
    private javax.swing.JPanel addJPanel;
    private javax.swing.JComboBox<String> assignJComboBox;
    private javax.swing.JLabel assignJLabel;
    private javax.swing.JPanel assignTabJPanel;
    private javax.swing.JScrollPane descriptionJScrollPane;
    private javax.swing.JTextArea descriptionJTextArea;
    private javax.swing.JLabel detailsActivityJLabel;
    private javax.swing.JTextField detailsActivityJTextField;
    private javax.swing.JScrollPane detailsDescriptionJScrollPanel;
    private javax.swing.JTextArea detailsDescriptionJTextArea;
    private javax.swing.JLabel detailsIdJLabel;
    private javax.swing.JTextField detailsIdJTextField;
    private javax.swing.JPanel detailsJPanel;
    private javax.swing.JScrollPane detailsNotesJScrollPane;
    private javax.swing.JTextArea detailsNotesJTextArea;
    private javax.swing.JLabel detailsSMPJLabel;
    private javax.swing.JTextField detailsSMPJTextField;
    private javax.swing.JList<String> detailsSkillsJList;
    private javax.swing.JScrollPane detailsSkillsJScrollPane;
    private javax.swing.JLabel detailsWeekJLabel;
    private javax.swing.JTextField detailsWeekJTextField;
    private javax.swing.ButtonGroup eowButtonGroup;
    private javax.swing.JLabel estimatedTimeJLabel;
    private javax.swing.JSpinner estimatedTimeJSpinner;
    private javax.swing.JLabel ewoJLabel1;
    private javax.swing.JRadioButton ewoNoJRadioButton;
    private javax.swing.JRadioButton ewoYesJRadioButton;
    private javax.swing.JButton forwardJButton;
    private javax.swing.ButtonGroup interrruptableButtonGroup;
    private javax.swing.JLabel interruptJLabel;
    private javax.swing.JRadioButton interruptNoJRadioButton;
    private javax.swing.JRadioButton interruptYesJRadioButton;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane mainJTabbedPane;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JComboBox<String> procedureJComboBox;
    private javax.swing.JLabel procedureJLabel;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JComboBox<String> siteJComboBox;
    private javax.swing.JLabel siteJLabel;
    private javax.swing.JComboBox<String> typeJComboBox;
    private javax.swing.JLabel typeJLabel;
    private javax.swing.JLabel weekJLabel;
    private javax.swing.JSpinner weekJSpinner;
    private javax.swing.JLabel weekNumberJLabel;
    private javax.swing.JSpinner weekNumberJSpinner;
    // End of variables declaration//GEN-END:variables

    private void initTable(int n_week) {
        try {
            activityList = MaintenanceActivity.getMaintenanceActivities(connection);
            DefaultTableModel activitiesTabelModel = (DefaultTableModel) activitiesJTable.getModel();
            activitiesTabelModel.setNumRows(0);
            activitiesTabelModel.fireTableDataChanged();
            activityList.forEach((MaintenanceActivity activity) -> {
                if (activity.getWeek() == n_week) {
                    System.out.println(activity.getActivityId());
                    activitiesTabelModel.addRow(new Object[]{activity.getActivityId(), activity.getSite().getName(), activity.getTypology().getName(), activity.getEstimatedIntervention() + " min."});
                }
            });

        } catch (SQLException ex) {
            Logger.getLogger(PlannerGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void initValues() {
        initTable(0);
        initTypeComboBox();
        initProcedureComboBox();
        initSiteComboBox();
        initAssigneComboBox();
    }

    private void initTypeComboBox() {
        try {
            LinkedList<Typology> typologyList = Typology.getTypologies(connection);
            typologyList.forEach(typology -> {
                typeJComboBox.addItem(typology.getName());
            });

        } catch (SQLException ex) {
            Logger.getLogger(PlannerGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void initProcedureComboBox() {
        try {
            LinkedList<Procedure> procedureList = Procedure.getProcedures(connection);
            procedureList.forEach(procedure -> {
                procedureJComboBox.addItem(procedure.getName());
            });

        } catch (SQLException ex) {
            Logger.getLogger(PlannerGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void initSiteComboBox() {
        try {
            LinkedList<Site> siteyList = Site.getSites(connection);
            siteyList.forEach(site -> {
                siteJComboBox.addItem(site.getName());
            });

        } catch (SQLException ex) {
            Logger.getLogger(PlannerGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void initAssigneComboBox() {
        try {
            LinkedList<User> userList = User.getUsers(connection);
            userList.forEach(user -> {
                if (user.getRole().equals("Maintainer")) {
                    assignJComboBox.addItem(user.getUsername() + ": " + user.getName() + " " + user.getSurname());
                }
            });

        } catch (SQLException ex) {
            Logger.getLogger(PlannerGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
