/*
ALTER DATABASE "maintenanceDB" OWNER TO postgres;
ALTER DEFAULT PRIVILEGES
revoke INSERT, SELECT, UPDATE, DELETE ON TABLES from  team14;
DROP USER IF EXISTS team14;
*/

CREATE USER team14 WITH PASSWORD 'team14';
ALTER DATABASE "maintenanceDB" OWNER TO postgres;
ALTER DEFAULT PRIVILEGES GRANT INSERT, SELECT, UPDATE, DELETE ON TABLES TO team14; 
ALTER DEFAULT PRIVILEGES GRANT USAGE ON SEQUENCES TO team14;

