-- Database: maintenanceDB

-- DROP DATABASE "maintenanceDB";

CREATE DATABASE "maintenanceDB"
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Italian_Italy.1252'
    LC_CTYPE = 'Italian_Italy.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

ALTER DEFAULT PRIVILEGES
GRANT ALL ON TABLES TO postgres;

ALTER DEFAULT PRIVILEGES
GRANT DELETE, UPDATE, SELECT, INSERT ON TABLES TO team14;

ALTER DEFAULT PRIVILEGES
GRANT ALL ON SEQUENCES TO postgres;

ALTER DEFAULT PRIVILEGES
GRANT USAGE ON SEQUENCES TO team14;