/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.dialogs;

import com.team14.se.maintenanceapp.MaintenanceActivity;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author emale
 */
public class EditNoteJDialog extends javax.swing.JDialog {

    private final int activity_id;
    private final MaintenanceActivity activity;
    private final String oldNote;
    private final Connection conn;

    /**
     * Creates new form EditNoteJDialog
     * 
     * @param parent parent frame
     * @param modal if modal
     * @param conn database connection
     * @param activity note activity
     */
    public EditNoteJDialog(java.awt.Frame parent, boolean modal, Connection conn, MaintenanceActivity activity) {
        super(parent, modal);
        initComponents();
        this.activity = activity;
        this.activity_id = activity.getActivityId();
        this.oldNote = activity.getNote();
        this.conn = conn;
        noteJTextArea.setText(activity.getNote());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        noteJTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Note");
        setResizable(false);

        noteJTextArea.setColumns(20);
        noteJTextArea.setRows(5);
        jScrollPane1.setViewportView(noteJTextArea);

        jLabel1.setText("Edit Note:");

        jButton1.setText("Edit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String newNote = noteJTextArea.getText();
        if (newNote.equals(oldNote)) {
            JOptionPane.showMessageDialog(rootPane, "You haven't made any changes to the note", "No change", JOptionPane.INFORMATION_MESSAGE);
        } else {
            activity.setNote(newNote);
            try {
                MaintenanceActivity.updateMaintenanceActivity(conn, activity, activity_id);
                JOptionPane.showMessageDialog(rootPane, "Note changed successfully", "Change Saved", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();

            } catch (SQLException ex) {
                Logger.getLogger(EditNoteJDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea noteJTextArea;
    // End of variables declaration//GEN-END:variables
}
